### ISSUE TITLE
Internal error occured!

### ISSUE THREAD

**Issue by Teomaniaforreal** [devhid/PEX-Rankup#10]
Whenever i try to rankup this happens:

[00:13:53 INFO]: Teomania issued server command: /rankup
[00:13:53 INFO]: Could not find current group of Teomania.
[00:13:53 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rankup' in plugin PEX-Rankup v2.3.5-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-db6de12-930a59c]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-db6de12-930a59c]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-db6de12-930a59c]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-db6de12-930a59c]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-db6de12-930a59c]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-db6de12-930a59c]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-db6de12-930a59c]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-db6de12-930a59c]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-db6de12-930a59c]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-db6de12-930a59c]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-930a59c]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-930a59c]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-930a59c]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at net.devhid.pexrankup.commands.RankupCommand.onCommand(RankupCommand.java:45) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-db6de12-930a59c]

This is my config:

#===============================================[ Notes ]================================================#
# name: PEX-Rankup                                                                                       #
# author: Hid                                                                                            #
# version: 2.3.5                                                                                         #
# notice: This plugin will work with both Java 7 and 8.                                                  #
#========================================================================================================#

MAIN:
  prefix-enabled: true
  prefix: "&4Rankup &8// &7"
  no-permission: "&cYou do not have permission to execute this command."
  improper-usage: "&cImproper usage. Proper usage for this command: /rankup | ranks | setrank <player> <rank>."
  invalid-sender: "&cInvalid sender. This command can only be performed by a player."
  player-offline: "&cThe specified player is currently offline."

RANKUP:
  last-rank: 'FREE'
  last-rank-message: "&cYou already have the last rank."

  not-enough-money: "&7You need &c${cost} &7to rank up to &c{rank}&7."
  rank-up-message:
      player-message: "&aYou have successfully ranked up to {rank}."
      broadcast: true
      broadcast-message: "&c{username} &7has ranked up to &c{rank}&7."

  rank-list: "&cHere are all the ranks and their costs:"
  rank-list-format: "&4 {rank} &7- &c$&7{cost}"

  setrank-invalid-rank: "&cThe specified rank is not in the rank ladder."
  setrank-success: "&7You have set &c{username}'s&7 rank to &c{rank}&7."
  setrank-received: "&7Your rank has successfully been set to &c{rank}&7."

  scoreboard-next-rank-none: "N/A"

  execute-commands-upon-setrank: {}
  execute-commands-upon-rankup: {/eco set {username} 2000}

LADDER:
   A: 0
   B: 5000
   C: 10000
   D: 15000
   E: 20000
   F: 25000
   G: 50000
   H: 100000
   I: 200000
   J: 250000
   K: 500000
   L: 750000
   M: 1000000
   N: 1250000
   O: 1500000
   P: 1750000
   Q: 2000000
   R: 2500000
   S: 3000000
   T: 3500000
   U: 4000000
   V: 4500000
   W: 5000000
   X: 6500000
   Y: 7000000
   Z: 90000000
   prestigeA: 10000000
   prestigeB: 10000
   prestigeC: 20000
   prestigeD: 30000
   prestigeE: 50000
   prestigeF: 100000
   prestigeG: 200000
   prestigeH: 300000
   prestigeI: 400000
   prestigeJ: 500000
   prestigeK: 750000
   prestigeL: 1000000
   prestigeM: 2000000
   prestigeN: 3000000
   prestigeO: 5000000
   prestigeP: 6000000
   prestigeQ: 7000000
   prestigeR: 8000000
   prestigeS: 9000000
   prestigeT: 10000000
   prestigeU: 11000000
   prestigeV: 12000000
   prestigeW: 130000000
   prestigeX: 140000000
   prestigeY: 150000000
   prestigeZ: 160000000
   prestigeA2: 17000000
   prestigeB2: 50000
   prestigeC2: 100000
   prestigeD2: 150000
   prestigeE2: 200000
   prestigeF2: 250000
   prestigeG2: 500000
   prestigeH2: 1000000
   prestigeI2: 2000000
   prestigeJ2: 2500000
   prestigeK2: 5000000
   prestigeL2: 7500000
   prestigeM2: 10000000
   prestigeN2: 12500000
   prestigeO2: 15000000
   prestigeP2: 20000000
   prestigeQ2: 30000000
   prestigeR2: 40000000
   prestigeS2: 50000000
   prestigeT2: 60000000
   prestigeU2: 80000000
   prestigeV2: 90000000
   prestigeW2: 100000000
   prestigeX2: 110000000
   prestigeY2: 120000000
   prestigeZ2: 150000000
   CrimelordA: 200000000
   CrimelordB: 100000
   CrimelordC: 200000
   CrimelordD: 300000
   CrimelordE: 500000
   CrimelordF: 1000000
   CrimelordG: 2000000
   CrimelordH: 3000000
   CrimelordI: 5000000
   CrimelordJ: 6000000
   CrimelordK: 7500000
   CrimelordL: 10000000
   CrimelordM: 15000000
   CrimelordN: 20000000
   CrimelordO: 25000000
   CrimelordP: 30000000
   CrimelordQ: 50000000
   CrimelordR: 75000000
   CrimelordS: 100000000
   CrimelordT: 110000000
   CrimelordU: 120000000
   CrimelordV: 130000000
   CrimelordW: 150000000
   CrimelordX: 175000000
   CrimelordY: 2000000000
   CrimelordZ: 225000000
   FREE: 300000000

What could be the cause, and how can i fix this? because my server depends on your plugin!

**Comment by devhid** [comment]
For the execute-commands-upon-rankup option in your config, it should be:

```
execute-commands-upon-rankup:
- eco give {username} 2000
```
Also make sure that all of your groups in your permissions.yml are spelled correctly and match the group names in the config.yml exactly. My plugin is case sensitive with the groups in PEX.

**Comment by Teomaniaforreal** [comment]
Thanks, i was wondering it would be something like that! Thanks again, and merry christmas!
