### ISSUE TITLE
Config problem?

### ISSUE THREAD

**Issue by Markbona** [devhid/PEX-Rankup#13]
Im having a problem with this pexrankup thing, 
Here is the error
[09:49:15 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rankup' in plugin PEX-Rankup v2.3.5-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_172]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_172]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.lang.NullPointerException
        at net.devhid.pexrankup.commands.RankupCommand.onCommand(RankupCommand.java:45) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
        ... 14 more

Here is my config
#===============================================[ Notes ]================================================#
# name: PEX-Rankup                                                                                       #
# author: Hid                                                                                            #
# version: 2.3.5                                                                                         #
# notice: This plugin will work with both Java 7 and 8.                                                  #
#========================================================================================================#

MAIN:
  prefix-enabled: true
  prefix: "&4Rankup &8// &7"
  no-permission: "&cYou do not have permission to execute this command."
  improper-usage: "&cImproper usage. Proper usage for this command: /rankup | ranks | setrank <player> <rank>."
  invalid-sender: "&cInvalid sender. This command can only be performed by a player."
  player-offline: "&cThe specified player is currently offline."

RANKUP:
  last-rank: 'Z'
  last-rank-message: "&cYou already have the last rank."

  not-enough-money: "&7You need &c${cost} &7to rank up to &c{rank}&7."
  rank-up-message:
      player-message: "&aYou have successfully ranked up to {rank}."
      broadcast: true
      broadcast-message: "&c{username} &7has ranked up to &c{rank}&7."

  rank-list: "&cHere are all the ranks and their costs:"
  rank-list-format: "&4 {rank} &7- &c$&7{cost}"

  setrank-invalid-rank: "&cThe specified rank is not in the rank ladder."
  setrank-success: "&7You have set &c{username}'s&7 rank to &c{rank}&7."
  setrank-received: "&7Your rank has successfully been set to &c{rank}&7."

  scoreboard-next-rank-none: "N/A"

  execute-commands-upon-setrank: {}
  execute-commands-upon-rankup: {}

LADDER:
   Member: 0
   Peasant: 10000
   Servant: 30000
   Citizen: 75000
   Amateur: 150000
   Novice: 250000
   Knowledgable: 500000
   Experienced: 1000000
   Seasoned: 5000000
   Advanced: 12500000
   Elite: 50000000
   Expert: 100000000
   Veteran: 500000000

Thank you

**Comment by Markbona** [comment]
I also have the version of pex as 

PermissionsEx v1.23.4
--

.

**Comment by devhid** [comment]
Your configuration file is valid YAML, so no issues with that.

Your problem might be that the rank names in the **LADDER** section of the config do not exactly match the group names in your PermissionsEx configuration file.
